export const SESSION_AUTHORIZE_SUCCESS = 'SESSION_AUTHORIZE_SUCCESS';
export const SESSION_AUTHORIZE_FAIL = 'SESSION_AUTHORIZE_FAIL';
export const SESSION_AUTHORIZE_REQUEST = 'SESSION_AUTHORIZE_REQUEST';
