export const SESSION_AUTHORIZE_SUCCESS = 'SESSION_AUTHORIZE_SUCCESS';
export const SESSION_AUTHORIZE_FAIL = 'SESSION_AUTHORIZE_FAIL';
export const SESSION_AUTHORIZE_REQUEST = 'SESSION_AUTHORIZE_REQUEST';
export const SESSION_SIGN_OUT_REQUEST = 'SESSION_SIGN_OUT_REQUEST';
export const SESSION_SIGN_OUT_ERROR = 'SESSION_SIGN_OUT_ERROR';
export const SESSION_SIGN_OUT_SUCCESS = 'SESSION_SIGN_OUT_SUCCESS';
