export const TASKS_LIST_ITEM_REQUEST = 'TASKS_LIST_ITEM_REQUEST';
export const TASKS_LIST_ITEM_FAIL = 'TASKS_LIST_ITEM_FAIL';
export const TASKS_LIST_ITEM_SUCCESS = 'TASKS_LIST_ITEM_SUCCESS';
export const TASK_UPDATE_SUCCESS = 'TASK_ITEM_UPDATE_SUCCESS';
export const TASK_UPDATE_FAIL = 'TASK_UPDATE_FAIL';
export const TASK_CREATE_SUCCESS = 'TASK_CREATE_SUCCESS';
export const TASK_CREATE_FAIL = 'TASK_CREATE_FAIL';
