export const TASKS_LISTS_REQUEST = 'TASKS_LIST_REQUEST';
export const TASKS_LISTS_FAIL = 'TASKS_LIST_FAIL';
export const TASKS_LISTS_SUCCESS = 'TASKS_LIST_SUCCESS';
export const CREATE_TASK_LIST_REQUEST = 'CREATE_TASK_LIST_REQUEST';
export const CREATE_TASK_LIST_SUCCESS = 'CREATE_TASK_LIST_SUCCESS';
export const CREATE_TASK_LIST_FAIL = 'CREATE_TASK_LIST_FAIL';